### ISSUE TITLE
[Feature Request] Some UX Alterations to the GUI

### ISSUE THREAD

**Issue by Darkosto** [Harmonised7/project_mmo#10]
Hello! 

I'm not sure if you're open to suggestions for the mod, but I'd love to give some helpful feedback. 

I'm a big fan of the mod and it's mechanics. Thanks for taking the time to make it and keep it up to date!

1. I really enjoy the icons and creative use of mousing over them to switch to another image. However, I feel that I need to mouse over to see what each of them does which isn't ideal. Is it possible to use the same icons but have the text directly next to them so you can see all the options right away. I think this could save some time when trying to find the information.

2. Following up on the glossary page, there are a number of icons that have extremely similar artwork. This makes it difficult to determine what they are to a new player. Some text may help clear this up but maybe having a different image could help too? (Maybe just a color change to differentiate?)

3. The page showing current XP for the player might benefit from a single bar to show total and current XP. This might simplify things a bit more and give the information a bit faster.

4. I've noticed a lot of the numbers in the guide have many decimal places. Is it possible to limit this and clean it up?

5. In the config pages, the buttons on the right hand side are a bit confusing. They seem to do the same on both config pages but are labeled differently. Can these be given a bit more info and made consistent? (The 'R' button for 'MAX' and 'Reset')

6. I also think localizing the config titles might help out some players who are not as literate in setting up configs.

7. This is more of a visual comment, but would you be able to substitute the on/off sliders in the config to be a button instead?

Most of these are a personal preference but I think it might help out some players. Let me know if I can follow up with any more information, I'd love to help out in any way I can! Thanks again for making the mod it has a lot of cool features and has so much potential beyond that! Have a great day! 

Darkosto

**Comment by Harmonised7** [comment]
I do not look at issues on Github. Please contact me on Discord, instead.
