### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by GraveCarver** [Harmonised7/project_mmo#12]
Modpack: Age of Summer by Kreezxil - Version:1.16.3 - forge: 34.1.25 - pmmo update: 3.31.7

Latest Log file, was no Crash cause JDKlauncher will not realize it crashed.
[Latest Log.zip](https://github.com/Harmonised7/project_mmo/files/5480245/Latest.Log.zip)

Pastebin of the NullPointer
https://pastebin.com/rh1VW4bY

Another Grab from Log file of what is there for atleast 900k lines
https://pastebin.com/AtfAq9pv

If you need anything else, Tell Kreezxil or message me on Discord GraveCarver#2051

**Comment by Harmonised7** [comment]
I do not look at issues on Github. Please contact me on Discord, instead.
