### ISSUE TITLE
Unexpected Error (XP Overlay) (FATAL ERROR IN XPOVERLAY GUI!!!!)

### ISSUE THREAD

**Issue by Coraline77447** [Harmonised7/project_mmo#13]
Hi, I was just playing my modded Minecraft 1.16.4 and I was in a ocean biome trying to break a drowned spawner (at a custom drowned dungeon generated by Repurposed Structures mod) and after I broke the spawner with MY OWN BARE HANDS since my mining skill isn't at level 10 which I don't understand how I'm supposed to level up mining without a pickaxe, even without a wooden pickaxe and if I mine stone with my bare hands I would just break the stone and probably won't earn any XP for mining stone with my bare hands or would get very little mining XP like possibly +0.65 or so mining XP but my crash report ain't about that even tho it's my biggest issue but what my crash report is is way more important than not being able to mine anything at all. Anyways here's the crash report, well... A piece of it but if you require all of it then I can provide the entire crash report to you:

https://pastebin.com/BgyySeSk

Also my Minecraft version is 1.16.4, mod version was 3.37.1 (downloaded and installed the latest version (3.38) which I hope you guys had changed the mining skill for the wooden pickaxe, even tho I don't exactly mind the challange but not being able to actually level up the mining skill without a pickaxe except for bare hands till mining 10 will take a LONG TIME when punching stone with bare fists while earning little to no mining XP which I would either disable the mining skill till you guys rebalance it for the wooden pickaxe or I would just suck it up and punch stone for dayz to only earn little to no mining XP... Btw before PMMO 3.38 how I was able to level up the mining skill was by finding monster apwners and break them with my bare hands in peaceful difficulty and would get +55.00 mining XP which was or may still be my only way to level up the mining skill till i reach mining level 10...), and my forge version is 35.1.12

(BTW when I crashed I had just broke a drowned spawner with my bare hands in an ocean biome which took me some time to do it but I'm lucky that I have the Artifacts mod installed with the Scuba Artifact thing that grants me permanent water breathing effect when warn in Crious or else I would've been drowning then would've drowned even tho I'm currently in peaceful difficulty since I only have leather boots and cap ATM and them drowneds with their deadly tridents would own my face big time. I know that everything that I've just said ain't important whatsoever but why can't I share ya my experiences with ya and what could've happened to me if I didn't have Artifacts mod?... One more thing, how I know that this crash was caused by Project MMO is in the crash report on the first few lines says pmmo which stands for Project MMO and that's why I'm here reporting this, Also sorry for writing such a long crash report and possibly most of it may not make any sense especially at the end and I can't explain why this crash happened when it shouldn't have in the first place....)

EDIT: I'm only playing in modded singleplayer not modded multiplayer on a server and my so called "modpack" is just a bunch of mods put into my mods folder (Project MMO included or else I wouldn't have reported this issue in the first place obviously)

EDIT!: This just in! I've found a fatal error with Project MMO's XPOverlay GUI at line!! There's something going on with it that you guys may need to take a deeper look at it immediately!!! And how I've found this information was from the log files when the crash happened thanks to Blame mod! 

Log file of Coraline World 1.16.4 (Modded) (CRASHED/UNABLE TO REJOIN!):
[2020-12-18-1.log](https://github.com/Harmonised7/project_mmo/files/5719417/2020-12-18-1.log)

Sure this fatal error may have been fixed but is the fix temporary or permanent??? Cause if this happens again and my redo world of Coraline World 1.16.4 (Modded) crashes and is un-joinable then the fix wasn't enough! Why I'm typing like this in a serious way is cause I like this mod and it's so much fun to level up the skills to unlock stuff that I would otherwise be able to get in bulk like say a diamond pickaxe. I like the challenge that Project MMO brings to the game and I'm going to have a mod called Dungeons Mobs that brings Minecraft Dungeons mobs to Minecraft Java Edition and have them only be defeated when the player is at a certain level in combat skill just like the silverfish in order to defeat them.

**Comment by Harmonised7** [comment]
Hey, try 3.39.3 c: I have reworked old GUI code, I believe your issues should be gone with this version. It will be out further today

**Comment by Coraline77447** [comment]
Alright, btw I've downloaded 3.39.2 which would unfortunately have the issue till the release of 3.39.3. Also I hope that I wasn't rude in the report and sorry for the very, very long report, I just kept editing to add my findings that were about the problem.

**Comment by Harmonised7** [comment]
This was solved a while back.
I do not look at issues on Github. In the future, please contact me on Discord, instead.
