### ISSUE TITLE
(Feature Request) External player data storage

### ISSUE THREAD

**Issue by Druwan-ctrl** [Harmonised7/project_mmo#20]
Hi everyone, 

I'm suggesting this because having an external data storage would finally allow mmo-like waterfall/velocity setups. 

Since you can't have a large modpack and a lot of players on one server using an external data storage metod as MySQL/MongoDB/PostgreSQL can allow medium/big communities to play as a whole, having different rpg realms for the actual gameplay but with the possibility to move and meet other players to cooperate/pvp/wars/events. 

I'm currently building such a server, and would love to be able to let players move between servers instead of locking them in one realm. Since this mod has become pretty much essential for the gameplay that I want for my users I really hope this feature can be implemented!

ps: I know that this will be a pain to read, but I'm working with the 1.12.2 version (because sponge)

**Comment by Harmonised7** [comment]
I do not look at issues on Github. Please contact me on Discord, instead.
