### ISSUE TITLE
Multiple things

### ISSUE THREAD

**Issue by fusionbolt18** [Harmonised7/project_mmo#21]
1: The night vision thing with swimming is really annoying and half the time it constantly flickers on and off every single frame like a strobe light.

1a: We tried setting the requirement for unlocking that to a really high level so it wouldn't happen but it straight up didn't work.

1b: We tried resetting our swimming levels and then setting them back but it still happened, which means that it is just straight up ignoring the config.

2: So many things say to look at "data.json" but it STRAIGHT UP DOES NOT EXIST.

**Comment by Harmonised7** [comment]
I do not look at issues on Github. Please contact me on Discord, instead.
