### ISSUE TITLE
[Contribution] Increased Modded Ores Support for smelting, mining

### ISSUE THREAD

**Issue by Solxanich** [Harmonised7/project_mmo#22]
I would like to suggest adding additional support for modded ores in smelting, mining, salvaging.
Namely, more in the default files.

Myself, as I have been planning to use this in MP with some friends as a tack on to TNP Limitless 3, I have "unofficially" added ores that I could find in the modpack from Thermal, Astral, Silent, and some others based on my balancing knowledge and existing entries. 
If these files are suitable:
[modified jsons.zip](https://github.com/Harmonised7/project_mmo/files/5884304/modified.jsons.zip)
feel free to use.

**Comment by Harmonised7** [comment]
Perfect, thank you for your contribution! <3 Will be out with next release (above 3.41.3)
