### ISSUE TITLE
Cannot figure out how to use the level up command.

### ISSUE THREAD

**Issue by axelblade013** [Harmonised7/project_mmo#27]
I'm running a server in 1.12.2 and I'm trying to use the level up command that I found in the config files to give out rewards to the players for various tasks. I put the command in thats given and all that players receive is the cookie but it doesnt do anything to their skills. the syntax im using is /give Player minecraft:cookie 1 0 {endurance:100} as the file says to do and while they get a cookie, they dont get any xp out of it.

**Comment by didis54** [comment]
https://discord.gg/5NVNkNB
