### ISSUE TITLE
unable to disable a skill, using xp config

### ISSUE THREAD

**Issue by HomelessZombie** [Harmonised7/project_mmo#29]
**By posting this on Github, I agree to the fact that this message will likely be forgotten, and abandoned, and that I should've instead went to the official Discord, where the dev is actually active, and will provide help.**

**Describe the bug**
unable to set xp gain for a skill to 0 to disable it

**To Reproduce**
1. Go to xp_multiplier_dimension.json
2. add "Skill_Name": 0

**Expected behavior**
sets xp gain for skill to be 0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Forge Version: 14.23.5.2854 
 - Mod Version:1.12-3.44.3

**Additional context**
![image](https://user-images.githubusercontent.com/80185317/110227737-7d42fb00-7ec9-11eb-8596-ee4b9bb6e56f.png)

**Comment by Harmonised7** [comment]
https://discord.gg/5NVNkNB
