### ISSUE TITLE
Make the experience of all skills shared between party members

### ISSUE THREAD

**Issue by recon88** [Harmonised7/project_mmo#33]
Hey, I just went through the config and the code to find out that only certain skills are part of the experience sharing system.
Would love to have that expanded to all skills which is default on but toggleable in config.

**Comment by Harmonised7** [comment]
https://discord.gg/5NVNkNB

**Comment by recon88** [comment]
Just close your issue tracker if you don't wanna answer the tickets to save people's time... Not gonna join that and not gonna report anything again in that case.

**Comment by Harmonised7** [comment]
I was not aware I can do that. Thank You.

To answer your question, even though you gave a thumbs down, which was rather immature:

I have no idea what you are talking about, there is no skill-specific ignoring of xp gained regarding parties.
