### ISSUE TITLE
Magic and Engineering

### ISSUE THREAD

**Issue by magerooster** [Harmonised7/project_mmo#7]
MC Version: 1.15.2
Forge Version: 31.2.21
PMMO Version: 3.2
Other mods mentioned: Botania build 386, Create 0.2.4d

Are these skills still a work in progress or are they implemented? I tried adding experience rewards to a block break event and a crafting event and neither of them seemed to work. The tooltips on the items display what I expect but I just get default amounts for both:

Under block break:

	"botania:livingrock": {
		"mining": 1,
		"magic": 10
	},			
	"botania:livingwood": {
		"woodcutting": 1,
		"magic": 10
	}

Breaking these blocks gave 2 mining and 2 woodcutting respectively, and no magic.

Under crafting:

	"create:andesite_alloy": {
		"crafting": 5,
		"engineering": 5
	},

(Again, got the default crafting experience amount and no engineering experience. Not in the TAB list, not in the scrolling exp earned, not in the "P" GUI.)

![skills](https://user-images.githubusercontent.com/924157/85365462-40b9a580-b4da-11ea-9db8-9859cec68173.png)

But the tooltips of these items show they should be working:

![lrock](https://user-images.githubusercontent.com/924157/85365358-094af900-b4da-11ea-9342-b9bc987518fa.png)

![andalloy](https://user-images.githubusercontent.com/924157/85365231-c9841180-b4d9-11ea-9f9f-1c0187c5d584.png)

**Comment by Harmonised7** [comment]
This is indeed an issue, though I have never heard this issue, and heard several people use this mechanic without fail... Would you please contact me on Discord to solve this asap? I'm terrible at forum-y places

Thanks!

**Comment by Harmonised7** [comment]
Hey I believe you joined the Discord and the issue was that the block was player-placed

Please tell me if this is a correct assumption, as in that case, that is intended mechanics
