### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by WenXin20** [Harmonised7/project_mmo#8]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Project MMO v3.7`

When I try to join my server, I get an Internal Server Error, and the log spits out a bunch of errors.
[Server Log](https://gist.github.com/WenXin20/4dff0496a0e51f07476c528037de5231)

**Comment by Harmonised7** [comment]
If this issue was caused by my mod, it should now be fixed! <3
