### ISSUE TITLE
Upgrading Enchants do not work on a server...

### ISSUE THREAD

**Issue by spdkils** [Harmonised7/project_mmo#9]
I tested this in a creative world, and it works fine. You get the intended enchant...

However once on a server, and using the same mechanics it does not upgrade enchants to higher levels. (You do get the SUCCESS message...)

start a server... (not local)
Set level in salvaging to 50
grab a stack of unbreaking III books.
grab an anvil

Start smashing books....

It says it's upgraded but none of them upgrade.

I also have quark installed, and single player and multiplayer that works
Single player this mod works...
on the server it does not.

**Comment by spdkils** [comment]
After a bunch more testing... it works... but you MUST throw the item on the ground and never let it touch your inventory.... take from finger, throw on ground, pick back up, has enchant. If it goes to your inventory it doesn't "stick"

**Comment by Harmonised7** [comment]
I see, this is a known glitch while other mods are present, and unfortunately, I was not yet able to fix it! But!

You can disable all anvil interactions in the /config/pmmo-common.toml

That's the best I can help you for now, will try to fix!
